-- MySQL Script generated by MySQL Workbench
-- Sat Sep 29 12:47:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TED
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TED` ;

-- -----------------------------------------------------
-- Schema TED
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TED` DEFAULT CHARACTER SET utf8 ;
USE `TED` ;

-- -----------------------------------------------------
-- Table `TED`.`Administrators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Administrators` ;

CREATE TABLE IF NOT EXISTS `TED`.`Administrators` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`password`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Professionals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Professionals` ;

CREATE TABLE IF NOT EXISTS `TED`.`Professionals` (
  `idProfessional` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(32) NOT NULL,
  `profilePictureURI` VARCHAR(4096) NOT NULL,
  `employmentStatus` TINYTEXT NULL,
  `employmentInstitution` TINYTEXT NULL,
  `description` TEXT NULL,
  `professionalExperience` MEDIUMTEXT NULL,
  `educationBackground` MEDIUMTEXT NULL,
  `skills` MEDIUMTEXT NULL,
  `professionalExperienceVisibility` TINYINT NOT NULL DEFAULT 1,
  `educationBackgroundVisibility` TINYINT NOT NULL DEFAULT 1,
  `skillsVisibility` TINYINT NOT NULL DEFAULT 1,
  `registrationDate` DATETIME NULL,
  PRIMARY KEY (`idProfessional`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Articles` ;

CREATE TABLE IF NOT EXISTS `TED`.`Articles` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `idAuthor` INT NOT NULL,
  `postedDate` DATETIME NOT NULL,
  `content` MEDIUMTEXT NULL,
  `containsFiles` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_Articles_Professional_idx` (`idAuthor` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_Professional`
    FOREIGN KEY (`idAuthor`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`ArticleFilePaths`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`ArticleFilePaths` ;

CREATE TABLE IF NOT EXISTS `TED`.`ArticleFilePaths` (
  `idArticleFile` INT NOT NULL AUTO_INCREMENT,
  `filePath` VARCHAR(4096) NOT NULL COMMENT 'Contains references to stored files such as images, videos, etc\n\nThis implementation assumes that each file can only be used in one article. It would be akward to have the same reference to the same file in two different articles due to the way articles are posted.',
  `idArticle` INT NOT NULL,
  INDEX `fk_UploadedFilePaths_Articles1_idx` (`idArticle` ASC) VISIBLE,
  PRIMARY KEY (`idArticleFile`),
  CONSTRAINT `fk_UploadedFilePaths_Articles1`
    FOREIGN KEY (`idArticle`)
    REFERENCES `TED`.`Articles` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`ConnectedProfessionals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`ConnectedProfessionals` ;

CREATE TABLE IF NOT EXISTS `TED`.`ConnectedProfessionals` (
  `idProfessional1` INT NOT NULL COMMENT ' Order of Professional IDs does not matter due to the reflective property.',
  `idProfessional2` INT NOT NULL COMMENT ' Order of Professional IDs does not matter due to the reflective property.',
  `connectionDate` DATE NOT NULL,
  PRIMARY KEY (`idProfessional1`, `idProfessional2`),
  INDEX `fk_ConnectedProfessionals_Professional2_idx` (`idProfessional2` ASC) VISIBLE,
  CONSTRAINT `fk_ConnectedProfessionals_Professional1`
    FOREIGN KEY (`idProfessional1`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConnectedProfessionals_Professional2`
    FOREIGN KEY (`idProfessional2`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`ConnectionRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`ConnectionRequests` ;

CREATE TABLE IF NOT EXISTS `TED`.`ConnectionRequests` (
  `idAsker` INT NOT NULL,
  `idReceiver` INT NOT NULL,
  `requestDate` DATETIME NOT NULL,
  PRIMARY KEY (`idAsker`, `idReceiver`),
  INDEX `fk_ConnectionRequests_Professional2_idx` (`idAsker` ASC) VISIBLE,
  CONSTRAINT `fk_ConnectionRequests_Professional1`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConnectionRequests_Professional2`
    FOREIGN KEY (`idAsker`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`ArticleComments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`ArticleComments` ;

CREATE TABLE IF NOT EXISTS `TED`.`ArticleComments` (
  `idComment` BIGINT NOT NULL AUTO_INCREMENT,
  `idArticle` INT NOT NULL,
  `idWrittenBy` INT NOT NULL,
  `comment` TEXT NOT NULL,
  `dateWritten` DATETIME NOT NULL,
  `seen` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_ArticlesComments_Articles1_idx` (`idArticle` ASC) VISIBLE,
  PRIMARY KEY (`idComment`),
  INDEX `idWrittenBy_idx` (`idWrittenBy` ASC) VISIBLE,
  CONSTRAINT `fk_ArticlesComments_Articles1`
    FOREIGN KEY (`idArticle`)
    REFERENCES `TED`.`Articles` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ArticlesComments_Professionals1`
    FOREIGN KEY (`idWrittenBy`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`ArticleInterests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`ArticleInterests` ;

CREATE TABLE IF NOT EXISTS `TED`.`ArticleInterests` (
  `idArticle` INT NOT NULL COMMENT ' No need for ArticleInterest ID !',
  `idInterestShownBy` INT NOT NULL,
  `dateShown` DATETIME NOT NULL,
  `seen` TINYINT NOT NULL DEFAULT 0,
  INDEX `fk_ArticleInterests_Professional1_idx` (`idInterestShownBy` ASC) VISIBLE,
  PRIMARY KEY (`idArticle`, `idInterestShownBy`),
  CONSTRAINT `fk_ArticleInterests_Articles1`
    FOREIGN KEY (`idArticle`)
    REFERENCES `TED`.`Articles` (`idArticle`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ArticleInterests_Professional1`
    FOREIGN KEY (`idInterestShownBy`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Conversations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Conversations` ;

CREATE TABLE IF NOT EXISTS `TED`.`Conversations` (
  `idProfessional1` INT NOT NULL,
  `idProfessional2` INT NOT NULL,
  `lastMessageSent` DATETIME NOT NULL COMMENT 'Needed in order to sort out the messages of a Professional.',
  PRIMARY KEY (`idProfessional1`, `idProfessional2`),
  INDEX `fk_Conversations_Professionals2_idx` (`idProfessional2` ASC) VISIBLE,
  CONSTRAINT `fk_Conversations_Professionals1`
    FOREIGN KEY (`idProfessional1`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversations_Professionals2`
    FOREIGN KEY (`idProfessional2`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Messages` ;

CREATE TABLE IF NOT EXISTS `TED`.`Messages` (
  `idMessage` BIGINT NOT NULL AUTO_INCREMENT,
  `idProfessional1` INT NOT NULL,
  `idProfessional2` INT NOT NULL,
  `idSentByProf` INT NOT NULL,
  `text` TEXT NULL,
  `timeSent` DATETIME NOT NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `fk_Messages_Professionals1_idx` (`idSentByProf` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_Conversations1`
    FOREIGN KEY (`idProfessional1` , `idProfessional2`)
    REFERENCES `TED`.`Conversations` (`idProfessional1` , `idProfessional2`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Professionals1`
    FOREIGN KEY (`idSentByProf`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Ads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Ads` ;

CREATE TABLE IF NOT EXISTS `TED`.`Ads` (
  `idAd` INT NOT NULL AUTO_INCREMENT,
  `idPublishedBy` INT NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `postedDate` DATETIME NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idAd`),
  INDEX `fk_Ads_Professionals1_idx` (`idPublishedBy` ASC) VISIBLE,
  CONSTRAINT `fk_Ads_Professionals1`
    FOREIGN KEY (`idPublishedBy`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TED`.`Applications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TED`.`Applications` ;

CREATE TABLE IF NOT EXISTS `TED`.`Applications` (
  `idApplication` INT NOT NULL AUTO_INCREMENT,
  `idAd` INT NOT NULL,
  `idApplicant` INT NOT NULL,
  `applyDate` DATETIME NOT NULL,
  `note` TEXT NOT NULL,
  `seen` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idApplication`),
  INDEX `fk_Applications_Professionals1_idx` (`idApplicant` ASC) VISIBLE,
  CONSTRAINT `fk_Applications_Ads1`
    FOREIGN KEY (`idAd`)
    REFERENCES `TED`.`Ads` (`idAd`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Applications_Professionals1`
    FOREIGN KEY (`idApplicant`)
    REFERENCES `TED`.`Professionals` (`idProfessional`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS myuser;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'myuser' IDENTIFIED BY 'MYUSERSQL';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert Admin with credentials:
-- 	Email: admin@uoa.gr
-- 	Password: admin
-- -----------------------------------------------------

INSERT INTO Administrators VALUES ('admin@uoa.gr', '4ca67c2f748361a579d70c022d4552c37035e87b1833e92934daebed58a2f83a');

